### ISSUE TITLE
Make `isinplace` a trait

### ISSUE THREAD

**Issue by mauro3** [JuliaDiffEq/DiffEqBase.jl#10]
I think `isinplace` should be a trait and not a type parameter.  Thoughts?

**Comment by ChrisRackauckas** [comment]
Probably. That seems to make sense.

The `inplace` story should likely get more complex. Currently I have it so that way you can give inplace functions and non-inplace functions, which is useful since equations on immutables (numbers) cannot be inplace. And I always divided it by `Number` and `AbstractArray`. A non-inplace function on an `AbstractArray` would auto-convert to an in-place function so the `AbstractArray` methods would work.

There are two things here. The first is generalizing these ideas, and secondly it's making them more compatible. The ideas should be generalized by making it `Indexable` (`AbstractArray`) and `NotIndexable` (not `AbstractArray`). This would expand `Number` to include ApproxFun `Fun` types directly, and fully support their changing length nature.

However, if you check the OrdinaryDiffEq integrators, to support these two types I have two dispatches for each method. There has to be a better way:

```julia
du = f(t,u,du)
```

I wonder if that works correctly and gets the right performance...

**Comment by ChrisRackauckas** [comment]
It's hard to do because `isinplace` has a different meaning (different number of parameters) depending on the type of problem. This would mess with promotion, so it has to be placed during the construction of the type. This would require some kind of parametric trait to do correctly, so I'll close unless something comes up.
