### ISSUE TITLE
Allow `solver` to be passed as a keyword argument?

### ISSUE THREAD

**Issue by Datseris** [JuliaDiffEq/DiffEqBase.jl#109]
Hi! Is it possible to do this? I am guessing that it would mess-up the method that "automatically detects a solver".

**Comment by ChrisRackauckas** [comment]
This can get caught in the case of someone using DifferentialEquations.jl. It will always have a (relatively quick) dynamic dispatch since it really does have to be a positional arg due to the dispatch mechanism. I think that just doing https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/260 and setting it up to error when given as a keyword argument would be a good thing too. Right now it just passes it along without warning you its ignored which is bad behavior.

**Comment by ChrisRackauckas** [comment]
These will now catch algorithms passed as `alg` and swap them into the dispatch spot. 

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/solve.jl#L5-L21
