### ISSUE TITLE
[Suggestion] Some defaults on recipes

### ISSUE THREAD

**Issue by aytekinar** [JuliaDiffEq/DiffEqBase.jl#40]
Personally, I like it when the axes' limits do not change during an animation. Would you be interested in applying default `xlims` and `ylims` in the `@recipe` to make `animate` have only the series changing, but not the limits of the axes? What do you think? Mine is of course just a taste...

**Comment by ChrisRackauckas** [comment]
Yes, that's a good idea. We'd need some way to realize its an animation though.

**Comment by aytekinar** [comment]
cheating from your type structure, I had the below recipe for myself
```julia
@recipe function f(res::TimeResponse; outputs  = 1:size(res.y, 2), inputs = Int[],
  states = Int[])

  # some irrelevant stuff

  t_plotted = res.t

  ylims = Tuple[]
  y_plotted = res.y[:, [outputset...]]
  u_plotted = res.u[:, [inputset...]]
  x_plotted = res.x[:, [stateset...]]

  if !isempty(y_plotted)
    push!(ylims, (1.1*minimum(y_plotted), 1.1*maximum(y_plotted)))
  end
  if !isempty(u_plotted)
    push!(ylims, (1.1*minimum(u_plotted), 1.1*maximum(u_plotted)))
  end
  if !isempty(x_plotted)
    push!(ylims, (1.1*minimum(x_plotted), 1.1*maximum(x_plotted)))
  end

  layout  --> (numplots,1)
  link    --> :x
  xlims   --> (minimum(t_plotted), maximum(t_plotted))
  ylims   --> reshape(ylims, 1, length(ylims))

  xguide  --> "t (sec)"
  yguide  --> reshape(ylabs, 1, length(ylabs))
  label   --> [outputlab inputlab statelab]

  if !isempty(outputset)
    curplot += 1
    @series begin
      subplot   :=  curplot
      t_plotted[1:endidx], y_plotted[1:endidx,:]
    end
  end

  if !isempty(inputset)
    curplot += 1
    @series begin
      subplot   :=  curplot
      t_plotted[1:endidx], u_plotted[1:endidx,:]
    end
  end

  if !isempty(stateset)
    curplot += 1
    @series begin
      subplot   :=  curplot
      t_plotted[1:endidx], x_plotted[1:endidx,:]
    end
  end
end
```

I know, you have a different use case from mine. But, still, I guess you can get the maximum value (and, possibly extend it by some margin, as I have done it) and then propose it using `xlim --> ...`. In my case, I have different series plotted on different subplots. Hence, I needed a vector of tuples. But, in your case, after applying `f`s in tuples, still you might get the maximum value.

Do you actually need if it's animation or not?

**Comment by ChrisRackauckas** [comment]
>I know, you have a different use case from mine. 

I always set axis limits in animations for this reason. I would like a good solution here.

>Do you actually need if it's animation or not?

I guess not. Technically you can set `tslocation` to make a plot on a for a shorter starting time, but that isn't even documented. I'm not sure that's useful anyways. Always setting the plot limits using the max/mins could theoretically work. The issue with this is that when plotting the shorter solution these are not actually calculated. I think this is really pointing out the fact that we need to do something differently with animations. 

You would think it would get the recipe for all time, and plot out truncations of it. But in actuality, since it just repeatedly calls the recipe, it does the whole calculation of the recipe for each frame of the animation. This is a bad ad-hoc solution which makes this handling animations in a more sophisticated way more difficult.

**Comment by aytekinar** [comment]
true that. it takes a whole lot of time even for 40 frames. however, I should not complain. it came for free with only 3 method overloads.

**Comment by ChrisRackauckas** [comment]
We might want `animate` to move to RecipesBase. Otherwise we have to play dumb with an iterator. I wonder if @mkborregaard would allow that as part of https://github.com/JuliaPlots/RecipesBase.jl/pull/16 . That would complete my happiness, since that's something I've asked for a long time!

**Comment by aytekinar** [comment]
what happened Tom, by the way? Did he stop contributing to `Plots`? Well, I am trying to rely only on `RecipesBase`. However, since all the plotting functionality is integrated in the JuliaBox images now, I can require `Plots`, too. Otherwise, I couldn't even `Pkg.add` `DifferentialEquations` together with `PyPlot` :) Now, at least, I can `Pkg.add("OrdinaryDiffEq")` and just `using PyPlot` :)

**Comment by ChrisRackauckas** [comment]
Tom is mostly off to other adventures. But yes, that PR is to make it so that way all recipes can be done without a Plots requirement. Adding a way to make animations without Plots without requiring that it simply plot whatever comes out of the iterator interface would be a huge flexibility win.

**Comment by ChrisRackauckas** [comment]
`animate` added to RecipesBase PR.

**Comment by mkborregaard** [comment]
But not the animate macro? Is this sufficient to write recipes? I've never written animated recipes, truth be told.

**Comment by aytekinar** [comment]
At least `animate` being in `RecipesBase` will allow us to `import RecipesBase: animate` to overload it for our custom types.

**Comment by ChrisRackauckas** [comment]
>But not the animate macro? Is this sufficient to write recipes? I've never written animated recipes, truth be told.

You can't really write recipes for animate. But you'd need to bring a ton of Plots.jl over for `@animate` to work. Instead, just using `animate` works because the default just works on an iterator. So technically you could achieve anything like this by doing

```julia
animate(AnimationIteratorWrapper(my_type))
```

so that way you use an alternative iteration that is good for animation. But `animate(my_type::MyType)` would make this much easier, and could let you setup kwargs for doing this. It's a much nicer API.

**Comment by mkborregaard** [comment]
I feel a bit like we haven't ruled out the other idea, of making a new package RecipesTools with all this extra goodness in it, which would allow for the nice API while keeping RecipesBase super slim for standard library packages.

**Comment by ChrisRackauckas** [comment]
Implemented.
