### ISSUE TITLE
Broadcasting a DataArray

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBase.jl#63]
Does broadcasting a DataArray return a DataArray? I think in the long run we should do something like

https://github.com/JuliaDiffEq/MultiScaleArrays.jl/blob/master/src/math.jl#L9

**Comment by devmotion** [comment]
No. 
```julia
julia> using DiffEqBase
julia> type SimType{T} <: DEDataArray{T}
           x::Array{T,1}
           f1::T
       end
julia> u0 = SimType{Float64}([10;10], 0.0)
2-element SimType{Float64}:
 10.0
 10.0
julia> u0 .+ 0.5.*[0.2, -0.5]
2-element Array{Float64,1}:
 10.1 
  9.75
```
That's exactly the reason why the data array tests fail in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/104: 
https://github.com/devmotion/OrdinaryDiffEq.jl/blob/d5e5da8a239ab5568bb30578b79b209b416e29d6/src/initdt.jl#L27
creates `u₁` of type Array and not SimType, and hence in the function call in
https://github.com/devmotion/OrdinaryDiffEq.jl/blob/d5e5da8a239ab5568bb30578b79b209b416e29d6/src/initdt.jl#L29
the field `f1` can not be accessed.

**Comment by devmotion** [comment]
Actually I think this behaviour is intended and desired.

1. Regular broadcasting, such as shown in the example above, should return a broadcast result on the contained array `x` of the involved DEDataArrays. We do not know whether and how we should handle arbitrary user-defined fields (it might not even by possible to apply the desired function to those fields), so the default behaviour should be not to try to broadcast these fields. If another behaviour is desired by the user `_containertype`, `promote_containertype`, and `broadcast_c` should be implemented for a specific subtype of DEDataArray.

2. Broadcast assignments are handled differently: in that case the default behaviour will be to update the contained array `x` of the destination with the broadcast result. This is shown by
```julia
julia> type SimType{T} <: DEDataArray{T}
                  x::Array{T,1}
                  f1::T
              end
julia> u0 = SimType{Float64}([10;10], 0.0)
2-element SimType{Float64}:
 10.0
 10.0
julia> u₁ = similar(u0)
2-element SimType{Float64}:
 10.0
 10.0
julia> u₁.f1 = 3
3
julia> @. u₁ = u0 + 0.5*[0.2, -0.5]
2-element SimType{Float64}:
 10.1 
  9.75
julia> u₁.x
2-element Array{Float64,1}:
 10.1 
  9.75
julia> u₁.f1
3.0
julia> u0.f1
0.0
```
The return type will still be a DEDataArray since only `x` is updated. This seems to be a sane default behaviour, and so https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/104 can be fixed by just defining
```julia
u₁ = similar(u0)
```
before assigning values to it.

However, I discovered a problem if `x` is not a vector. I'll open a separate PR for that.

**Comment by devmotion** [comment]
Can this be closed? I think there is no issue at all since this can not be solved on a general level - the user has to define a desired broadcast behaviour anyway.

Of course, because of the example above without these user definitions `DEDataArrays` won't work with not in-place algorithms because of the example above. But updating an existing `DEDataArray` with broadcasting already works as expected - it just updates its array `x` (this can be seen e.g. in the examples at https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/64 and https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/65). This is the only reasonable behaviour since we do not know how to handle any additional fields, I think. So in-place methods should work just fine with `DEDataArrays`.

**Comment by ChrisRackauckas** [comment]
>This is the only reasonable behaviour since we do not know how to handle any additional fields, I think.

Couldn't this be done with `@generated` functions? But I agree that it shouldn't be necessary: it would add overhead and wouldn't effect what's given to the user at all I think.

**Comment by ChrisRackauckas** [comment]
I guess it would be impossible to know which one to take coefficients from. I see.
