### ISSUE TITLE
Accessing time in residual function of TwoPointBoundaryProblems

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaDiffEq/DiffEqBase.jl#81]
I find it very restrictive to pass only `u[1]` and `u[end]` to the residual function of `TwoPointBVProblem` therefore one cannot access the tspan.

One possibility is to pass solution types that only hold `u[1]` and `u[end]` as `u`. The other possibility I see is to explicitly pass `tspan`.

**Comment by ChrisRackauckas** [comment]
Yeah, I was thinking about this when doing the change. It seems that BVP boundaries are now the only thing that don't follow the `u,p,t` pattern. Wrapping the `u` in a tuple before sending is essentially free, so that's an option. Basically it would `(res,u,p,t)` where `u` is the `u[1]` and `u[end]` tuple, while `t[1]` and `t[end]` correspond to that. We can put `t` on the end for the other BVP as well for consistency.

**Comment by BeastyBlacksmith** [comment]
I like that choice

**Comment by ChrisRackauckas** [comment]
Great. I'll implement it as the last changes of the v4.0.0 upgrade. This will make it easy to wrap other multi-point BVP solvers like those in ODEInterface.jl too, so I'll get on that.
