### ISSUE TITLE
Ditch ODETestProblem in favor of overloading

### ISSUE THREAD

**Issue by mauro3** [JuliaDiffEq/DiffEqBase.jl#9]
As we use function overloading for many extra functions, why not use it for the analytic solution as well?  (Now that we're using traits dispatch would work too.)  Would seem more consistent to me.

**Comment by ChrisRackauckas** [comment]
That makes sense. How would the trait dispatch happen on the problem for `build_solution`?

**Comment by ChrisRackauckas** [comment]
What's the way to make this consistent for IMEX and SDEs? Overload the analytic solution to just the first function?

**Comment by mauro3** [comment]
For `build_solution`, probably just us a `if has_ana(prob)`. Maybe , by convention but all the overloads in `prob.f` unless it is specific to `prob.g`?

**Comment by ChrisRackauckas** [comment]
That could work. I won't get around to this for awhile since the gain is in internal design only, but it would be an easy PR (mostly just needs some clear changes to DiffEqBase and DiffEqDevTools. I think there's one other place which references using an ODESolution? Tests will find it).

**Comment by mauro3** [comment]
Does `Pkg.test("DifferentialEquations")` run all tests or do they need to be run one by one?

**Comment by ChrisRackauckas** [comment]
They have to be run separately, split by the features in each package. DifferentialEquations.jl just does the default algorithms. If we're keeping Solution and TestSolution separate, then there should really be almost nothing to change.  In the ecosystem, other tests may fail because of this kind of usage:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/test/ode/ode_feagin_tests.jl#L33

but the sources should all be written for `AbstractODEProblem` so they will not even see the change.

If you're also suggesting combining the two solution types, just worrying about DiffEqDevTools should be enough since it tests the tableaus (so the general testing workflow of ODEs as well), and does the testing for appxtrue and benchmarks which are related to the test solutions.

**Comment by ChrisRackauckas** [comment]
I actually don't think this is the right direction any more. Playing around with it, I realized that we would still have to split the `Solution` and `TestSolution` types if we want to have a `Solution` type be as simple as possible and not hold errors and analytical solutions (and it's good for dispatching on). But more importantly, placing these dispatches ends up very wonky. When you just have `f` for an ODE, it's fine. But what about IMEX? Some PDEs with plenty of functions? You start having to make a bunch of conventions which aren't easy to guess or document.

So for now I think we keep it for now. Since this part of the API isn't user-facing (only developers will ever have to create test problems / solutions), this is something that is not difficult to change later.
